version: '3.0'
services:
  apache:
    image: httpd
    volumes:
      - ./app:/usr/local/apache2/htdocs/
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    ports:
      - "8080:80"
    links:
      - mariadb:db
  php:    
     image: php:7.2-fpm
     volumes:
      - ./app:/usr/local/apache2/htdocs/
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    links:
      - mariadb:db
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mariadb